# Generated by Django 5.1.1 on 2024-10-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(blank=True, max_length=9, null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('date', models.DateField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('suspended', 'Suspended'), ('confirmed', 'Confirmed')], max_length=10)),
                ('test_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed positive', 'Confirmed Positive'), ('confirmed negative', 'Confirmed Negative')], max_length=20)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=30, null=True)),
                ('additional_information', models.TextField(help_text='Occupation, Travel History')),
            ],
        ),
    ]
